# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - SnakrAPI

on:
  push:
    branches:
      - Production
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://snakrdns.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_1f8f5199dbb7486a81a71e873fecc8ac }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e75ef20b745743a0836ba7619f161f82 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: snakrdns.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1f8f5199dbb7486a81a71e873fecc8ac }}/snakr:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'SnakrAPI'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7b090dc6bc8a427fb860ae124cabb08c }}
        images: 'snakrdns.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1f8f5199dbb7486a81a71e873fecc8ac }}/snakr:${{ github.sha }}'